Prevent adding events to closed stream controller
hivedb/hive pull request #1223
Opened 2023-07-25 15:05 UTC by krida2000

Resolves #1034

I had same issue using following code:

``` dart

await box.clear();
await box.close();

```

2023-07-26 15:19 UTC, themisir requested changes

2023-07-26 16:40 UTC, krida2000 commented on hive/lib/src/box/change_notifier.dart
> +    if (_streamController.isClosed) {
Oops, fixed

2023-07-28 23:07 UTC, themisir approved these changes

2023-07-28 23:09 UTC, merged

2023-08-18 05:50 UTC, bhavin-concetto commented
@themisir  when can we expect it to be released?